apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodesample
  labels:
    app: nodesample
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: nodesample
  template:
    metadata:
      labels:
        app: nodesample
    spec:
      containers:
        - name: nodesample
          image: nodesample:v2
          imagePullPolicy: Never
